### ISSUE TITLE
Thanks for this! ❤️ 

### ISSUE THREAD

**Issue by lirantal** [Financial-Times/snyk-cleanup-archived-repositories#1]
Cool stuff building this!

Just wanted to let you know that I added it now to this repo: https://github.com/snyk/awesome-snyk-community. If there's anything else you've been building on that you'd like to put there please feel welcome to raise a pull request 🚀

**Comment by arash123-g** [comment]
be happy

**Comment by JakeChampion** [comment]
Thank you @lirantal ☺️
